### ISSUE TITLE
sound/music - not working under linux?

### ISSUE THREAD

**Issue by rdbeni0** [ProfGarfield/ExtendedMusicForTOTPP#1]
hi, i am trying to enable sound (music and sound) under Linux

what i already did:
- i copied into "lua" and "Music" content into correct place
- civ2tot with TOTPP latest ver  0.18.4 is working without issues (only one minor issue - too small font, but its not related with sound/music)
- i can select in menu Game > "Pick Music" 
- I have already selected: "DirectShow sound" and "DirectShow music" and "Lua scripting" under TOTPP Launcher
- i have music in main menu (after launching the game), but not when i start scenario
- probably it's something with my wine/prefix/system package - something could be missing, but what?

**Comment by ProfGarfield** [comment]
The main menu music is actually a "sound effect," and is turned on and off by the "Sound Effects" setting in the game options menu (CTRL+O).  Make sure that in that menu, the "Music" option is turned on.

I installed Civ II using Lutris.  My instruction thread is here https://forums.civfanatics.com/threads/installing-test-of-time-in-linux-mint-20.666105/ (and there is a video at the bottom).  TOTPPv18 should be the same as v16, except for using this patch.

I used wine version: tkg-protonified-4.1-x86_64
Prefix architecture: 32 Bit

This version of wine is fine except for the Alpha Centauri movie at the end of the game.  A v6 version of wine fixes that, but occasionally momentarily reduces the game window to 1/4 size when saving/loading, which I find annoying when testing Lua code.

I don't know what to suggest for your font issue, since I haven't run into it.  (Font size is adequate on 1080p monitor.)  If you make the status window a bit larger, the font size increases there.

**Comment by rdbeni0** [comment]
Hi, i changed wine version (previously i used 3.0.3 with 32 bit prefix), and your patch working. 
I have sound/music now.
I installed game (with all patches) via: "wine-7.13" without dxvk - and after that everything is OK.

Maybe do you know how can i make larger font in "Viewing Pieces" window? I changed size via mouse, but font size didn't increased :( For 1080p font is little too small - but only in "Viewing Pieces" or "Moving Units" windows...

anyway, we can close this topic

EDIT: finally everything is fixed! I changed layout compistion via View > Map Layout
and now font size is good

**Comment by rdbeni0** [comment]
closed & fixed
